#!/usr/bin/env bash

## General ---------------------------------------------------#

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$BSPDIR/scripts"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1
#wmname LG3D

## Current theme ---------------------------------------------#

## Bspwm colors
BSPWM_FBC='#5294E2'
BSPWM_NBC='#1E2128'
BSPWM_ABC='#C778DD'
BSPWM_PFC='#98C379'

## Bspwm appearance
BSPWM_BORDER='2'
BSPWM_GAP='0'
BSPWM_SRATIO='0.50'

## Configurations --------------------------------------------#
# '' '' '' '' '' '' '' '' '' '' '' '' ''

## Manage Monitors and Workspaces
##
## Default Setup (Set 8 workspaces on each monitor)
default_workspaces() {
	for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
		bspc monitor "$monitor" -d '' '' '' '' '' ''
	done
}

## Two Monitors Setup (Laptop and external monitor, set 4 workspaces on each monitor)
two_monitors_workspaces() {
	# change these values according to your system
	# you can use `xrandr -q` to get the names of monitors
	INTERNAL_MONITOR="eDP"
	EXTERNAL_MONITOR="HDMI-A-0"
	if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
		bspc monitor "$EXTERNAL_MONITOR" -d '' '' ''
		bspc monitor "$INTERNAL_MONITOR" -d '' '' ''
		bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
	else
		bspc monitor "$INTERNAL_MONITOR" -d '' '' '' '' '' ''
	fi
}

## Three Monitors Setup (Laptop and two external monitor, 3-2-3 workspaces)
three_monitors_workspaces() {
	# again, change these values accordingly
	MONITOR_1="eDP"
	MONITOR_2="HDMI-A-0"
	MONITOR_3="HDMI-A-1"
	bspc monitor "$MONITOR_1" -d '' ''
	bspc monitor "$MONITOR_2" -d '' ''
	bspc monitor "$MONITOR_3" -d '' ''
	bspc wm -O "$MONITOR_2" "$MONITOR_1" "$MONITOR_3"
}

## Uncomment only one function according to your needs
default_workspaces
#two_monitors_workspaces
#three_monitors_workspaces

## Apply bspwm configurations
bspc config border_width "$BSPWM_BORDER"
bspc config window_gap "$BSPWM_GAP"
bspc config split_ratio "$BSPWM_SRATIO"

bspc config focused_border_color "$BSPWM_FBC"
bspc config normal_border_color "$BSPWM_NBC"
bspc config active_border_color "$BSPWM_ABC"
bspc config presel_feedback_color "$BSPWM_PFC"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

## remove all rules first
bspc rule -r *:*

## 1
bspc rule -a kitty desktop='^1' follow=on focus=on

## 2
bspc rule -a firefox desktop='^2' follow=on focus=on

## 3
bspc rule -a Insomnia desktop='^3' follow=on focus=on

## 4
bspc rule -a discord desktop='^4' follow=on focus=on

## 5
bspc rule -a Spotify desktop='^5' follow=on focus=on
declare -a files=(Pcmanfm Thunar qBittorrent)
for i in ${files[@]}; do
	bspc rule -a $i desktop='^5' follow=on focus=on
done

## 6
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr
	System-config-printer.py Pavucontrol Exo-helper-1
	Xfce4-power-manager-settings)
for i in ${settings[@]}; do
	bspc rule -a $i desktop='^6' state=floating follow=on focus=on
done

## Always Floating Apps
declare -a floating=(alacritty-float Pcmanfm Onboard Yad 'Firefox:Places'
	Viewnior feh Nm-connection-editor calamares Calamares)
for i in ${floating[@]}; do
	bspc rule -a $i state=floating follow=on focus=on
done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager bspc

# Lauch xsettingsd daemon
xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
if [[ ! $(pidof xfce-polkit) ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd -c "$BSPDIR"/sxhkdrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash ~/.fehbg

# Start mpd
exec mpd &

# Start bspwm scripts
bspbar
bspcomp
bspdunst
bspfloat &
