#!/usr/bin/env bash

# Import Current Theme
DIR="$HOME/.config/bspwm"
STYLE="qwik"
RASI="$DIR/themes/$STYLE/rofi/askpass.rasi"

# Rofi text dialog to get password
rofi -dmenu \
     -password \
     -i \
     -p "Root" \
     -theme ${RASI}
